### ISSUE TITLE
Blaster CAD broken by 1.10a update

### ISSUE THREAD

**Issue by ItsTheKais** [Kamefrede/rpsideas#12]
My Blaster CAD became a pink cube upon updating from 1.9e to 1.10a. According to the tooltip, it lost its assembly in the update:
![2018-12-01_15 21 27](https://user-images.githubusercontent.com/9879642/49333634-680af380-f57f-11e8-848b-95594bbc7bda.png)
I can still bring up its spell selection wheel and put it in the CAD Assembler to change bullets, but trying to fire it causes a "CAD too weak to cast" error. It also seems to have lost all its lenses.

**Comment by Kamefrede** [comment]
This was unfortunately a consequence of fixing a bug regarding the model of the blaster CAD. It was either having the CAD break by the update or always having the model broken. I apologize but I chose the latter, if you can I'd advise you to go into creative and swap it out.

**Comment by Kamefrede** [comment]
I'll add a warning on curseforge about this. I forgot to add one. Again, my apologies
