### ISSUE TITLE
[BUG] Conjure Ethereal Block not works

### ISSUE THREAD

**Issue by lublak** [Kamefrede/rpsideas#23]
if i replace it with Conjure Ethereal Block it conjure nothing:

![grafik](https://user-images.githubusercontent.com/44057030/50548826-9568c100-0c53-11e9-9fe2-4a08e4d4b9fa.png)

![grafik](https://user-images.githubusercontent.com/44057030/50548824-8aae2c00-0c53-11e9-9ac4-8028f37a98b5.png)

Conjure Block from the orignal psi mod works fine:

![grafik](https://user-images.githubusercontent.com/44057030/50548807-40c54600-0c53-11e9-829c-1991a8d55611.png)

![grafik](https://user-images.githubusercontent.com/44057030/50548804-32772a00-0c53-11e9-9446-151e1cbe09ad.png)

**Comment by Kamefrede** [comment]
Fixed on the next version.
