### ISSUE TITLE
Creative items [SUGGESTION]

### ISSUE THREAD

**Issue by ViciousGamer** [Kamefrede/rpsideas#29]
So the creative colorizer (forgot the name) is orange. What if i want to change the color?
I would suggest making a creative item a core type than a colorizer type.

**Comment by yrsegal** [comment]
🤔

**Comment by Kamefrede** [comment]
The creative items were dropped in favour of the colorizer, wouldn't make much sense to add them back. I'll look into a way to let you add a different colour to the colorizer.
