### ISSUE TITLE
Remove Block Properties

### ISSUE THREAD

**Issue by Math321** [Kamefrede/rpsideas#30]
**/u/Math321** _Today at 9:32 PM_
@sonic-tier addon releaser @Kamefrede Would it make sense to get rid of Block Properties as a piece, and just dump its functionality into each piece that currently cares about block properties?

**sonic-tier addon releaser** _Today at 9:32 PM_
sure

**/u/Math321** _Today at 9:33 PM_
It seems unnecessary to have Block Properties as its own piece except maybe for Debug purposes...

**Comment by yrsegal** [comment]
😠i'm for this, kame
