### ISSUE TITLE
[Crash] Some times for unknown reasons

### ISSUE THREAD

**Issue by Shiranuit** [Kamefrede/rpsideas#34]
Hi,
me and my friends have been using your mod on our private server, and some times when I try a new spell that i've made, they crash with this error :

[crash-2019-02-01_19.24.12-client.txt](https://github.com/Kamefrede/rpsideas/files/2822877/crash-2019-02-01_19.24.12-client.txt)

This crash was when I was spawning multiple circle in a sphere form :
[crash-2019-02-01_19.00.06-client.txt](https://github.com/Kamefrede/rpsideas/files/2822885/crash-2019-02-01_19.00.06-client.txt)

And for some reasons one of my friend instead of seeing multiple circles, he saw this 
![2019-02-01_19 16 10](https://user-images.githubusercontent.com/19224148/52142789-f6702400-2659-11e9-9494-281adae39cb6.png)

They have forge : forge-1.12.2-14.23.5.2809
And I have forge : forge-1.12.2-14.23.5.2796
We are using the version 2.1.5 of Random PSIdeas

Hope this help

**Comment by Kamefrede** [comment]
fixed in 279dfba
