### ISSUE TITLE
Can't find out what any of your items do.

### ISSUE THREAD

**Issue by TheUnderTaker11** [Kamefrede/rpsideas#37]
What does the Flash ring do? Gauss Pulse Rifle? Ebony/ivory armor and tools? Nothing about these items obviously gives way to their function, and after multiple google searches, I can't find a shred of information.

**Comment by yrsegal** [comment]
the ebony armor and tools are identical. They're just a visual upgrade.

**Comment by yrsegal** [comment]
The pulse rifle shoots pulse rounds or psi, and disables the PSI of enemies it hits

**Comment by yrsegal** [comment]
The flash ring is a portable programmable spell, with the downside that it costs 5x the normal psi cost to cast.

**Comment by TheUnderTaker11** [comment]
Alright thank you.
