### ISSUE TITLE
Crash when using visible entities on self.

### ISSUE THREAD

**Issue by GoldenBlaze** [Kamefrede/rpsideas#38]
Though I am using a few mods. I don't believe they involve this issue. when I try and use the Selector: Visible entities, to detect myself. The game crashes.

spell used:
{spellName:"Selector",uuidMost:-1765356264708878389L,validSpell:1b,spellList:[{data:{key:"selectorCaster"},x:3,y:2},{data:{params:{_target:1},key:"operatorEntityPosition"},x:3,y:3},{data:{params:{rpsideas.spellparam.viewer:3,_radius:4},key:"rpsideas.selector_visible_entities"},x:4,y:2},{data:{params:{_target:1,_position:3},key:"operatorClosestToPoint"},x:4,y:3},{data:{key:"constantNumber",constantValue:"1"},x:5,y:2},{data:{params:{_number:0,_target:3},key:"trickDebug"},x:5,y:3}],uuidLeast:-7683758476854095703L}

Crash log: https://hastebin.com/okolaqavab.cs

**Comment by yrsegal** [comment]
Fixed in https://github.com/Kamefrede/rpsideas/commit/c6b792b8157e7af968a651dfd9522397396cd090#diff-827ede02590687583650152d936fcde7
