### ISSUE TITLE
How to use the colorizers?

### ISSUE THREAD

**Issue by Akepla** [Kamefrede/rpsideas#51]
I am so sorry to ask about that...but I just cannot figure out how to use the colorizers of rpsideas. I cannot find a tutorial on the Internet, and it seems that I cannot change the color of the CAD, even if I used the liquid-ink colorizer(yes, its color can be changed before you assemble the CAD but how about afterwards? And what is the difference between this one and a completely white colorizer?) or with shift right click or so on. So can you explain how to use your colorizers or write an wiki? Or they are just simply WIP?

**Comment by Kamefrede** [comment]
Sorry about the lack of documentation, that will be fixed soon.
The liquid-ink colorizer is meant for you to customize by combining it with several dyes in the crafting table, essentially giving you the choice to pick from the full RGB layout.

As for changing the colorizer, that's not directly possible, but you can swap the colorizer in the CAD currently by placing the CAD in the crafting table with another colorizer and that will return the colorizer that was in the CAD to you.

I hope that clears it up, if not feel free to tell me your doubts!

**Comment by Akepla** [comment]
Wow that's so cool, thanks a lot!
