### ISSUE TITLE
Flowsuits

### ISSUE THREAD

**Issue by Feztacular** [Kamefrede/rpsideas#52]
Psi seems to have changed armor model in latest update, so ebony and ivory flowsuits textures are broken, godspeed!

**Comment by yrsegal** [comment]
Waiting on @wiiv to do retextures, since he was the one who did the remodel

**Comment by WitherTech** [comment]
Do you have a time estimate?

**Comment by Kamefrede** [comment]
> Do you have a time estimate?

Yes, will be fixed on the next update.
