### ISSUE TITLE
[SUGGESTION] Hybrid Colorizer + Creative (and some other thoughts)

### ISSUE THREAD

**Issue by radzo73** [Kamefrede/rpsideas#57]
TL;DR, I like rainbow colorizer + ebony CAD :(
Combining the Creative colorizer with another doesn't give the CAD creative stats...Can you change this?

Also, could you add in upgradable slots for Ebony/Ivory things?

**Comment by yrsegal** [comment]
No. The creative colorizer is meant to indicate, clearly, that it is a creative CAD, to anyone looking.

We're planning to add new sockets, yes.
