### ISSUE TITLE
Taking off CAD while holding Inline Caster causes crash on player tick

### ISSUE THREAD

**Issue by aalwardt** [Kamefrede/rpsideas#58]
I was holding my CAD, as well as an Inline caster which I had just created. I moved my CAD into the CAD assembler to change its loadout, and immediately I was kicked from my server, with the following crash log:

https://paste.dimdev.org/yodijehore.mccrash

Rejoining causes the crash again as soon as the player is ticked, making this unrecoverable without the use of external tools.

**Comment by Kamefrede** [comment]
Fixed
