### ISSUE TITLE
Shielded and Unstable Battery Causing Kicks

### ISSUE THREAD

**Issue by Rithsagea** [Kamefrede/rpsideas#64]
This issue was made on the psi issue tracker. I'm linking it here.

https://github.com/Vazkii/Psi/issues/514

Taking damage and jumping after while having a cad that has either a shielded or unstable battery causes a kick for "fatal error".

Hybrid flow is fine

**Comment by TheDeviantCrafter** [comment]
Copying over the logs:

Here's the exact message that appears in server chat when it happens: https://gist.github.com/TheDeviantCrafter/ca408cb4216d228d5e68e3946a95a021

Here's the entire log:
https://gist.github.com/TheDeviantCrafter/16b95493a7ea5fb9979756b277a2e764

**Comment by Kamefrede** [comment]
Fixed in 73dd2ad
