### ISSUE TITLE
Planar Normal Vector: floating point inaccuracy?

### ISSUE THREAD

**Issue by Mattomanx77** [Kamefrede/rpsideas#92]
When attempting to use Operator: Planar Normal Vector to create a 3x3 mining spell, for some reason or another blocks along x/y/z 0 did not mine 'correctly', and I noticed as well that the result of the operation was outputting very, very small floats (on the order of magnitude 10^-11 or smaller). Extracting the x/y/z of the vector, rounding them, and re-constructing would work as intended, however this is extremely not ideal.
I assume the very small decimals resulting from the operator are not intended.

**Comment by TheidenHD** [comment]
The issue is, that the value is multiplied with π.
I implementiert a Method without it witch should gif the correct value without it.
https://github.com/TheidenHD/rpsideas/releases/tag/2.4.3
