### ISSUE TITLE
Trick: Break Loop skips index of 1

### ISSUE THREAD

**Issue by mateskr692** [Kamefrede/rpsideas#93]
Writing a simple program to print the loop count with "Selector: Loopcast Index" subtract a constant, and break loop on that couses the gun to skip index of 1. For example, writing a program:

{spellName:"Break Loop",uuidMost:844845151554519088L,validSpell:1b,spellList:[{data:{params:{_number:0,_target:4},key:"trickDebug"},x:3,y:4},{data:{key:"constantNumber",constantValue:"3"},x:3,y:5},{data:{key:"selectorLoopcastIndex"},x:4,y:4},{data:{params:{_number2:3,_number3:0,_number1:1},key:"operatorSubtract"},x:4,y:5},{data:{params:{_number:3},key:"rpsideas.trick_break_loop"},x:5,y:5}],uuidLeast:-9196392210051170248L}

onto a loopcast bullet works fine for time or sometimes a couple, but then the Debug output gives: "0.0, 2.0, 3.0", meaning it skipped 1

**Comment by Kamefrede** [comment]
https://github.com/Vazkii/Psi/issues/596
Issue with the loopcast itself, not with break loop.
